apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopmicro
  namespace: shopmicro
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: shopmicro.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3001
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000