apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: shopmicro
data:
  loki.yaml: |
    server:
      http_listen_port: 3100

    auth_enabled: false

    common:
      path_prefix: /var/loki # wouldn't run without the path_prefix set
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      tsdb_shipper: # added this section based on loki docs to fix startup error
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
      filesystem:
        directory: /var/loki/chunks
